{
    'name': 'Device Management',
    'version': '1.0',
    'summary': 'Manage Devices and Assignments',
    'depends': ['base', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/device_type_views.xml',
        'views/device_brand_views.xml',
        'views/device_model_views.xml',
        'views/device_views.xml',
        'views/device_attribute_views.xml',
        'views/device_attribute_value_views.xml',
        'views/device_assignment_views.xml',
        'views/employee_inherit_views.xml',
        # 'views/device_attribute_assignment_views.xml',
        'actions.xml',
        'views/device_management_menu_views.xml',
    ],
    'application': True,
    'installable':True,
}
